### ISSUE TITLE
POST Error (on Windows)

### ISSUE THREAD

**Issue by laurenceHR** [ubidots/ubidots-php#1]
I got 
JSON parse error - No JSON object could be decoded
I have tried doing curl manually and I got the same error when the JSON is 
-X POST -d '{"value": 6}'
but whith 
-X POST -d "{\"value\":6}" 
all's ok u.u
Using Apache on Windows...

**Comment by woakas** [comment]
where are you running it?

**Comment by laurenceHR** [comment]
exactly I'm runing on nginx over windows...
y decided fork, and create another version but working with curl/curl package

**Comment by jotathebest** [comment]
closing
