### ISSUE TITLE
Loads the Data from Ubidots API to mySQL database

### ISSUE THREAD

**Issue by Adie305** [ubidots/ubidots-php#3]
Hi.. how to loads the data from the ubidots API to mySQL database? Im using Laravel framework. Is it possible to make request to API for example every 15 seconds to make sure that my database is updated with the latest value?

**Comment by jotathebest** [comment]
you should use the SQL native API https://www.php.net/manual/en/book.mysql.php, closing as this is not an issue related with the library.
